<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2151" started-at="2015-05-10T20:42:38Z" finished-at="2015-05-10T20:42:40Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2151" started-at="2015-05-10T20:42:38Z" finished-at="2015-05-10T20:42:40Z">
      <class name="com.FCI.SWE.Controller.UserControllerTessting">
        <test-method status="FAIL" signature="UserController()[pri:0, instance:com.FCI.SWE.Controller.UserControllerTessting@1ebd2621]" name="UserController" duration-ms="2128" started-at="2015-05-10T22:42:38Z" finished-at="2015-05-10T22:42:40Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<kamal> but was:<1234>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<kamal> but was:<1234>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at com.FCI.SWE.Controller.UserControllerTessting.UserController(UserControllerTessting.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserController -->
      </class> <!-- com.FCI.SWE.Controller.UserControllerTessting -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
